#!/bin/bash
#
# build-reference-deployment.sh - regenerate the committed build output of a
# reference deployment from its recorded inputs.
#
# Usage (from the repo root):
#   ./scripts/docs/build-reference-deployment.sh <deployment-name> [--check]
#   ./scripts/docs/build-reference-deployment.sh --all [--check]
#
# A reference deployment lives in docs/architecture/reference-deployments/<name>/
# and records the two files build.sh reads: '.env' and '.settings'. This script
# swaps them into the repo root, runs 'build.sh -q -n deployment-scripts', and
# writes the normalised output back as docker-compose.built.yml (plus the '.env'
# and '.settings' build.sh wrote, so the recorded inputs are a fixpoint, and
# build-command.txt, the 'docker compose ... config' line build.sh assembled). The
# operator's own .env/.settings/docker-compose.yml are restored afterwards.
#
# Normalisation pins the host-specific values docker compose bakes into the
# output so that rebuilds on different machines are diffable:
#   - bind-mount sources under this checkout are rewritten to the canonical
#     production checkout path (CANONICAL_REPO_DIR)
#   - bind-mount sources under $HOME are rewritten to the canonical home
#     (CANONICAL_HOME)
# Everything else that varies by host (mongo sizing, project name) is pinned in
# the recorded inputs themselves. See docs/architecture/ARCHITECTURE_DOCS_STANDARD.md §2.
#
# With --check, nothing under docs/ is written: the script exits 1 if the
# regenerated output differs from the committed file.
#
# Requirements: docker compose plugin (no daemon needed), yq. A site-specific
# compose/docker-compose.custom.yml must not be present (it would leak into the
# reference output); the script aborts if it is.

set -euo pipefail

CANONICAL_HOME="/home/pacefactory"
CANONICAL_REPO_DIR="$CANONICAL_HOME/scv2/git_clones/deployment-scripts"
PROJECT="deployment-scripts"
REF_ROOT="docs/architecture/reference-deployments"

usage() { sed -n '2,/^$/p' "$0" | sed 's/^# \{0,1\}//'; exit "${1:-0}"; }

[[ -f build.sh && -d compose ]] || { echo >&2 "run from the repository root"; exit 2; }

CHECK=0
TARGETS=()
for arg in "$@"; do
  case "$arg" in
    --check) CHECK=1 ;;
    --all) TARGETS=($(find "$REF_ROOT" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort)) ;;
    -h|--help) usage 0 ;;
    *) TARGETS+=("$arg") ;;
  esac
done
[[ ${#TARGETS[@]} -gt 0 ]] || usage 2

if [[ -e compose/docker-compose.custom.yml ]]; then
  echo >&2 "compose/docker-compose.custom.yml exists; move it aside before building reference deployments"
  exit 2
fi

REPO_DIR="$(pwd -P)"
STASH="$(mktemp -d)"
restore() {
  for f in .env .env.backup .settings docker-compose.yml; do
    rm -f "$f"
    [[ -e "$STASH/$f" ]] && mv "$STASH/$f" "$f"
  done
  rm -rf "$STASH"
}
for f in .env .env.backup .settings docker-compose.yml; do
  [[ -e "$f" ]] && mv "$f" "$STASH/$f"
done
trap restore EXIT

normalise() {
  # $1 = raw compose config output, stdout = normalised
  {
    echo "# BUILD OUTPUT - do not edit by hand."
    echo "# Generated by scripts/docs/build-reference-deployment.sh from the .env and"
    echo "# .settings in this directory. Re-run that script to update."
    sed -e "s#${REPO_DIR}#${CANONICAL_REPO_DIR}#g" \
        -e "s#${HOME}/scv2/videos#${CANONICAL_HOME}/scv2/videos#g" "$1"
  }
}

rc=0
for name in "${TARGETS[@]}"; do
  dir="$REF_ROOT/$name"
  [[ -f "$dir/.settings" ]] || { echo >&2 "$dir/.settings not found"; rc=1; continue; }
  echo "== $name"
  rm -f .env .env.backup .settings docker-compose.yml
  cp "$dir/.settings" .settings
  [[ -f "$dir/.env" ]] && cp "$dir/.env" .env

  # build.sh does not check the exit code of 'docker compose config'; validate the file.
  if ! ./build.sh -q -n "$PROJECT" </dev/null >"$STASH/build.log" 2>&1 \
     || [[ ! -s docker-compose.yml ]] || ! grep -q '^services:' docker-compose.yml; then
    echo >&2 "build failed for $name:"; tail -n 20 "$STASH/build.log" >&2
    rc=1; continue
  fi

  normalise docker-compose.yml >"$STASH/$name.built.yml"
  if (( CHECK )); then
    if ! diff -u "$dir/docker-compose.built.yml" "$STASH/$name.built.yml"; then
      echo >&2 "$name: committed output is stale"; rc=1
    else
      echo "$name: up to date"
    fi
  else
    mv "$STASH/$name.built.yml" "$dir/docker-compose.built.yml"
    grep -m1 '^docker compose ' "$STASH/build.log" > "$dir/build-command.txt" || true
    cp .settings "$dir/.settings"
    [[ -f .env ]] && cp .env "$dir/.env"
    echo "$name: wrote $dir/docker-compose.built.yml"
  fi
done
exit $rc
