#!/bin/bash
# render-glossary.sh: writes docs/architecture/glossary.md from the static
# vocabulary below plus scripts/docs/services.tsv and externals.tsv.
set -euo pipefail
source scripts/docs/lib.sh
out="docs/architecture/glossary.md"
{
  doc_header "Glossary" reference "scripts/docs/services.tsv" "scripts/docs/externals.tsv" "build.sh" "compose/docker-compose.*.yml"
  cat <<'MD'

# Glossary

The authoritative vocabulary for Pacefactory deployment documentation. Service
repos defer to this file. Terms are defined once here; other docs link to the
anchor instead of redefining them. Generated by `scripts/docs/render-glossary.sh`.

## Terms

| Term | Definition |
|---|---|
| <a id="site"></a>**site** | A physical client location. A site runs one or more deployments. |
| <a id="deployment"></a>**deployment** | One running Docker Compose project produced by `build.sh` on one host. Identified by its compose project name (`PROJECT_NAME`, default `deployment-scripts`). |
| <a id="build-profile"></a>**build profile** (or just **profile**) | A compose fragment `compose/docker-compose.<id>.yml` that `build.sh` can enable. Every enabled fragment is passed to `docker compose config` both as `-f <fragment>` and as `--profile <id>`. Unless qualified, "profile" in these docs means build profile. |
| <a id="compose-profile"></a>**compose profile** | Docker Compose's own `profiles:` key on a service. In this repo it is used only to make a service on-demand (not started by `docker compose up`): `record_video` and `stitch_videos` carry `profiles: [tools]`, and each `certbot` service carries its https-* profile id. The names coincide with build profile ids because `build.sh` passes `--profile <id>` for every enabled build profile. |
| <a id="forced-profile"></a>**forced profile** | A build profile that `build.sh` always enables and never prompts for: `base`, `custom`, `tools`, `expresso-010` (`build.sh:51-58`). |
| <a id="default-on-profile"></a>**default-on profile** | A prompted build profile whose default answer is yes when `.settings` has no answer for it: `social`, `rdb`, `node-red`, `mqtt-public`, `mqtts-public` (`build.sh:30-34, 42-48`). |
| <a id="sub-profile"></a>**sub-profile** | A build profile marked `x-pf-info.sub-profile: true`. It is skipped in the main prompt loop and offered only after a parent that lists it under `x-pf-info.sub-profiles` is enabled (`build.sh:185-249, 306-311`). |
| <a id="required-profile"></a>**required profile** | A build profile listed under another profile's `x-pf-info.required-profiles`. Enabling the dependant force-enables it without a prompt (`build.sh:255-287`). Only `ape` uses this (requires `expresso-010`, `rdb`). |
| <a id="setting"></a>**setting** | A variable declared under a fragment's `x-pf-info.settings`. `build.sh` prompts for it (unless `hidden: true`) and writes answered values to `.env`. See the [environment variable reference](../reference/environment-variables.md). |
| <a id="hidden-setting"></a>**hidden setting** | A setting with `hidden: true`: never prompted, written to `.env` with its default whenever its profile is enabled. Used to pass values from a sub-profile or parent to another fragment (`REALTIME_TAG_DEFAULT_GPU`, `MQTTS_CERT_SOURCE`, ...). |
| <a id="default-var"></a>**default_var** | A setting attribute naming another variable whose current value becomes the prompt default (`build.sh:149, 156-159`). |
| <a id="service"></a>**service** | One compose service, hence one container, in a deployment. Node IDs for services are the compose service name with `-` replaced by `_` (see below). |
| <a id="home-profile"></a>**home profile** | The build profile whose fragment defines a service's `image`. Other fragments may modify the service (environment, ports, volumes) but do not own it. |
| <a id="reference-deployment"></a>**reference deployment** | A named, committed combination of `.env` and `.settings` under `docs/architecture/reference-deployments/<name>/` with its built compose output and derived diagrams. See the [catalogue](reference-deployments/README.md). |
| <a id="build-script"></a>**build script** | `build.sh` at the repo root: assembles the enabled fragments into `docker-compose.yml`. See the [build script reference](../reference/build-script.md). |
| <a id="integration-type"></a>**integration type** | A class of external system the deployment exchanges data with, identified by an `ext_*` node ID and documented under [integrations](integrations/README.md). |
| <a id="flow"></a>**flow** | One directed exchange between two nodes (service, volume or external system) with a protocol and channel, recorded as a row of the flow table (`scripts/docs/flows.tsv`). |
| <a id="fragment"></a>**fragment** | One `compose/docker-compose.<id>.yml` file. |
| <a id="built-output"></a>**built output** | The `docker-compose.yml` that `docker compose config` writes at the end of `build.sh`; for reference deployments, the committed `docker-compose.built.yml`. |

## Protocol spellings

Use exactly these in flow tables and arrow labels: `RTSP`, `HTTP`, `HTTPS`,
`WS` (MQTT over WebSocket), `MQTT`, `MQTTS`, `MongoDB wire`, `Redis`,
`PostgreSQL`, `SQL` (client database, driver unknown), `SSH`, `file` (bind
mount or shared volume).

## Services

Node ID is the Mermaid ID used in every diagram in this repo. Owner kind:
`internal` = a Pacefactory repository (every repository listed was reviewed by
the technical lead); `third-party` = not a Pacefactory image, only its
configuration is owned here. Links to service-repo architecture docs follow the
standard path `docs/architecture/README.md` and may not exist yet in that repo.

| Service | Node ID | Image | Home profile | Owning repo | Owner kind | Purpose |
|---|---|---|---|---|---|---|
MD
  while IFS=$'\t' read -r svc id disp img repo kind purpose; do
    [[ "$svc" == \#* || -z "$svc" ]] && continue
    home=$(profile_of_service "$svc")
    echo "| \`$svc\` | \`$id\` | \`$img\` | [\`$home\`](profiles/$home.md) | [$(basename "$repo")]($repo) | $kind | $purpose |"
  done < "$SERVICES_TSV"
  cat <<'MD'

## External integration types

| Integration type | Node ID | Protocol(s) | Direction | Page | Description |
|---|---|---|---|---|---|
MD
  while IFS=$'\t' read -r id disp protos dir page desc; do
    [[ "$id" == \#* || -z "$id" ]] && continue
    echo "| $disp | \`$id\` | $protos | $dir | [$page](integrations/$page) | $desc |"
  done < "$EXTERNALS_TSV"
  cat <<'MD'

## Other node IDs

| Kind | ID pattern | Shape | Example |
|---|---|---|---|
| Named volume | `vol_<volume name with - as _>` | cylinder `id[("volume: name")]` | `vol_dbserver_data` |
| Compose network | `net_<network name>` | `subgraph net_<name>` | `net_external_network` |
| Host-published port | `port_<published>` / `port_eph_<service>_<target>` / `port_<ip>_<published>` | parallelogram `id[/"host :80"/]` | `port_80`, `port_eph_alert_processing_engine_5380`, `port_127_0_0_1_3006` |
| Deployment boundary | `deployment` | `subgraph deployment[...]` | |
| Human actor | `user_<role>` | stadium `id(["Role"])` | `user_operator` |
MD
} > "$out"
echo "wrote $out"
