#!/bin/bash
# render-env-reference.sh
# Writes docs/reference/environment-variables.md: every variable build.sh reads
# or that a compose fragment interpolates, grouped by profile. Derived from
# compose/docker-compose.*.yml (x-pf-info.settings and ${VAR} interpolations),
# build.sh and scripts/common/*.sh.
set -euo pipefail
source scripts/docs/lib.sh
out="docs/reference/environment-variables.md"; mkdir -p docs/reference
scan="$(mktemp)"

# Emit TSV: var<TAB>profile<TAB>service<TAB>key<TAB>container_var<TAB>expression<TAB>fallback<TAB>required<TAB>line
for f in compose/docker-compose.*.yml; do
  p="${f#compose/docker-compose.}"; p="${p%.yml}"
  awk -v prof="$p" '
    /^[^ #]/ { top=$1; sub(":","",top); svc=""; key="" }
    top=="services" && /^  [A-Za-z0-9_-]+:/ { svc=$1; sub(":","",svc); key="" }
    top=="services" && svc!="" && /^    [a-z_]+:/ { key=$1; sub(":","",key) }
    top=="services" && /\$\{/ {
      line=$0; cv=""
      if (key=="environment" && match(line, /- *"?[A-Z_0-9]+=/)) { cv=substr(line,RSTART,RLENGTH); gsub(/[-" =]/,"",cv) }
      rest=line
      while ((i=index(rest,"${"))>0) {
        rest=substr(rest,i); depth=0; expr=""
        for (j=1;j<=length(rest);j++) { c=substr(rest,j,1); expr=expr c; if (c=="{") depth++; if (c=="}") { depth--; if (depth==0) break } }
        inner=substr(expr,3,length(expr)-3)
        var=inner; sub(/[:?-].*/,"",var)
        fb=""; req="no"
        if (inner ~ /^[A-Za-z0-9_]+:\?/) { req="yes"; fb="" }
        else if (inner ~ /^[A-Za-z0-9_]+:-/) { fb=inner; sub(/^[A-Za-z0-9_]+:-/,"",fb); if (fb ~ /^\$\{/) fb="(nested) " fb }
        else if (inner ~ /^[A-Za-z0-9_]+$/) { req="yes (no fallback)" }
        printf "%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%d\n", var, prof, svc, key, cv, expr, fb, req, NR
        rest=substr(rest,length(expr)+1)
      }
    }' "$f" >> "$scan"
done

profiles_using() { awk -F'\t' -v v="$1" '$1==v {print $2}' "$scan" | sort -u | paste -sd, - | sed 's/,/, /g'; }
reaches() {
  awk -F'\t' -v v="$1" '$1==v { k=$3"."$4; if ($5!="") k=k"="$5; print k }' "$scan" | sort -u | sed 's/.*/`&`/' | paste -sd, - | sed 's/,/, /g'
}
fallbacks() { awk -F'\t' -v v="$1" '$1==v && $7!="" {print $7}' "$scan" | sort -u | sed 's/.*/`&`/' | paste -sd, - | sed 's/,/, /g'; }
required_of() { awk -F'\t' -v v="$1" '$1==v && $8!="no" {print $8}' "$scan" | sort -u | paste -sd, - | sed 's/,/, /g'; }
lines_of() { awk -F'\t' -v v="$1" '$1==v {print "compose/docker-compose."$2".yml:"$9}' "$scan" | sort -u | paste -sd, - | sed 's/,/, /g'; }

setting_field() { yq ".[\"x-pf-info\"].settings[\"$2\"].$3 // \"\"" "compose/docker-compose.$1.yml"; }
setting_line() { grep -n -m1 "^    $2:" "compose/docker-compose.$1.yml" | cut -d: -f1; }

row() { # var kind default required profiles reaches description defined
  printf '| `%s` | %s | %s | %s | %s | %s | %s | %s |\n' "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8"
}

{
  doc_header "Environment variable reference" reference "build.sh" "scripts/common/projectName.sh" "scripts/common/runYq.sh" "compose/docker-compose.*.yml"
  cat <<'MD'

# Environment variable reference

Every variable that `build.sh` reads, and every variable a compose fragment
interpolates into the built `docker-compose.yml`. Generated by
`scripts/docs/render-env-reference.sh`; do not edit by hand.

How to read this table:

- **Kind** is one of `setting` (declared under `x-pf-info.settings`, prompted by
  `build.sh` and written to `.env` when answered), `hidden setting` (declared with
  `hidden: true`; written to `.env` with its default whenever the profile is
  enabled, never prompted), `interpolation only` (read by a fragment but not
  declared as a setting, so it can only be set by editing `.env` or exporting it
  in the shell that runs `build.sh`), or `build.sh` (consumed by the build script
  itself).
- **Default** quotes the `x-pf-info` default exactly; `none` means there is no
  default. **Compose fallback** is the `${VAR:-x}` fallback inside the fragment
  when it exists; it applies when the variable is absent from `.env` and the
  environment.
- **Reaches service(s) as** is `service.key` or `service.environment=CONTAINER_VAR`
  in the fragment. A variable whose only destinations are environment entries of
  the same name is a passthrough; its semantics live in the owning service repo
  (see the [glossary](../architecture/glossary.md) for repo links).
- Within a profile, required variables come first, then alphabetical.

## `build.sh` and its helpers

| Variable | Kind | Default | Required | Profiles affected | Reaches service(s) as | Description | Defined in |
|---|---|---|---|---|---|---|---|
| `PROJECT_NAME` | build.sh | first project listed by `docker compose ls --all --quiet`, else `deployment-scripts` | no | all | compose project name (`--project-name`), volume and container prefixes | Set by `-n/--name`, restored from `.settings`, or confirmed interactively. Must match `^[a-z0-9][a-z0-9_-]*$`. | `scripts/common/projectName.sh:1-4,12-14`; `build.sh:66-70,461` |
| `QUIET_MODE` | build.sh | none | no | all | none | Set by `-q/--quiet`; also honoured if already exported in the environment. Suppresses all prompts and forces `.settings` to be saved. | `build.sh:71-74,103,167,293,320,393,450` |
| `DEBUG` | build.sh | none | no | all | none | Set by `-d/--debug`; prints the assembled `--profile` and `-f` strings. | `build.sh:75-78,431-435` |
| `KRB5CCNAME` | build.sh | (unset by the script) | no | all | none | Unset so a host Kerberos credential cache is never forwarded to containers. | `build.sh:12-13` |
| `MONGO_MEMORY_LIMIT_DEFAULT` | build.sh | `2g`, `4g`, `8g` or `16g` by host RAM tier (<12, <24, <48, >=48 GB); unset if `/proc/meminfo` is unreadable | no | base | `mongo.deploy.resources.limits.memory` (fallback inside `${MONGO_MEMORY_LIMIT:-...}`); prompt default for `MONGO_MEMORY_LIMIT` | Exported by build.sh so the compose fallback resolves. An explicit `MONGO_MEMORY_LIMIT` always wins. | `build.sh:120-134`; `compose/docker-compose.base.yml:100` |
| `MONGO_WIREDTIGER_CACHE_GB_DEFAULT` | build.sh | `0.5`, `1.5`, `3.5` or `7` by the same tiers | no | base | `mongo.command --wiredTigerCacheSizeGB` (fallback inside `${MONGO_WIREDTIGER_CACHE_GB:-...}`) | As above. | `build.sh:120-134`; `compose/docker-compose.base.yml:90` |
| `SAVE_SETTINGS` | build.sh | `true` in quiet mode, else answered interactively | no | all | none | Whether `.settings` is rewritten at the end of the run. | `build.sh:450-465` |
| `DOCKER_LOGOUT`, `DOCKER_PULL` | build.sh | none | no | all | none | Not read by build.sh; persisted into `.settings` if present so `update.sh` picks them up. | `build.sh:461-463`; `update.sh:24-33,71,130` |
| `YQ_USE_DOCKER`, `YQ_DOCKER_IMAGE` | build.sh | `0`, `mikefarah/yq:latest` | no | all | none | Hard-coded in the helper, not overridable. Docker fallback is used only when no `yq` is on `PATH`. `build.sh` requires mikefarah yq v4; the Python `yq` wrapper on `PATH` breaks the profile loop silently. | `scripts/common/runYq.sh:3-4,26-32` |
| `HOME` | interpolation only | inherited from the shell | yes (no fallback) | tools | `record_video.volumes`, `stitch_videos.volumes` (bind source `${HOME}/scv2/videos`) | The builder's home directory is baked into the output as the video storage path. | `compose/docker-compose.tools.yml:23,42` |

MD
  for f in compose/docker-compose.*.yml; do
    p="${f#compose/docker-compose.}"; p="${p%.yml}"
    settings=$(yq '.["x-pf-info"].settings // {} | keys | .[]' "$f")
    interp=$(awk -F'\t' -v prof="$p" '$2==prof {print $1}' "$scan" | sort -u)
    # interpolation-only vars are listed under the first profile (alphabetically) that uses them
    only=""
    for v in $interp; do
      [[ "$v" == HOME ]] && continue
      declared=$(for g in compose/docker-compose.*.yml; do yq "(.[\"x-pf-info\"].settings // {}) | has(\"$v\")" "$g"; done | grep -c true || true); [[ "$declared" == 0 ]] && declared=""
      [[ -n "$declared" ]] && continue
      first=$(awk -F'\t' -v v="$v" '$1==v {print $2}' "$scan" | sort -u | sed -n 1p)
      [[ "$first" == "$p" ]] && only="$only $v"
    done
    [[ -z "$settings" && -z "$only" ]] && continue
    echo "## Profile \`$p\`"
    echo
    echo "See [profile page](../architecture/profiles/$p.md)."
    echo
    echo "| Variable | Kind | Default | Required | Profiles affected | Reaches service(s) as | Description | Defined in |"
    echo "|---|---|---|---|---|---|---|---|"
    tmp="$(mktemp)"
    for v in $settings; do
      def=$(setting_field "$p" "$v" default); hid=$(setting_field "$p" "$v" hidden); dv=$(setting_field "$p" "$v" default_var); dsc=$(setting_field "$p" "$v" description | tr '\n' ' ' | trim)
      kind="setting"; [[ "$hid" == "true" ]] && kind="hidden setting"
      d="\`${def:-\"\"}\`"; [[ -z "$def" ]] && d='`""`'
      [[ -n "$dv" ]] && d="$d (prompt default taken from \`$dv\` when set)"
      fb=$(fallbacks "$v"); [[ -n "$fb" ]] && d="$d; compose fallback: $fb"
      req=$(required_of "$v"); req="${req:-no}"
      r=$(reaches "$v"); r="${r:-none (prompted only)}"
      [[ -z "$dsc" ]] && dsc="passthrough; see owning service repo"
      sortkey="1"; [[ "$req" != "no" ]] && sortkey="0"
      printf '%s\t%s\n' "$sortkey$v" "$(row "$v" "$kind" "$d" "$req" "$(profiles_using "$v")${settings:+}" "$r" "$dsc" "\`$f:$(setting_line "$p" "$v")\`; $(lines_of "$v")")" >> "$tmp"
    done
    for v in $only; do
      fb=$(fallbacks "$v"); d="none"; [[ -n "$fb" ]] && d="compose fallback: $fb"
      req=$(required_of "$v"); req="${req:-no}"
      sortkey="1"; [[ "$req" != "no" ]] && sortkey="0"
      printf '%s\t%s\n' "$sortkey$v" "$(row "$v" "interpolation only" "$d" "$req" "$(profiles_using "$v")" "$(reaches "$v")" "Not declared as a setting: set it by editing \`.env\`. Semantics in the owning service repo." "$(lines_of "$v")")" >> "$tmp"
    done
    sort -t$'\t' -k1,1 "$tmp" | cut -f2-
    rm -f "$tmp"
    echo
  done
} > "$out"
rm -f "$scan"
echo "wrote $out"
