x-pf-info:
  name: Autozone profile
  prompt: Enable the Autozone profile?
  description: Autozone detects activity zones from tracked object hulls by creating heatmaps and applying thresholds
  settings:
    AUTOZONE_TAG:
      default: latest

services:
  autozone:
    container_name: ${PROJECT_PREFIX:-}autozone
    hostname: ${PROJECT_PREFIX:-}autozone
    image: pacefactory/autozone:${AUTOZONE_TAG:-latest}
    restart: always
    logging:
      driver: local
    volumes:
      - "autozone-data:/home/scv2/volume"
    networks:
      - external_network
      - autozone_network
    environment:
      - "MONGODB_ENABLED=true"
      - "MONGODB_URI=mongodb://${PROJECT_PREFIX:-}autozone_mongo:27017"
      - "DBSERVER_BASE_URL=http://${PROJECT_PREFIX:-}dbserver:8050"
      - "USE_DOCKER_VOLUME=true"
    depends_on:
      - dbserver
      - autozone_mongo

  autozone_api:
    container_name: ${PROJECT_PREFIX:-}autozone_api
    hostname: ${PROJECT_PREFIX:-}autozone_api
    image: pacefactory/autozone_api:${AUTOZONE_TAG:-latest}
    restart: always
    logging:
      driver: local
    networks:
      - external_network
      - autozone_network
    environment:
      - "MONGODB_URI=mongodb://${PROJECT_PREFIX:-}autozone_mongo:27017"
    depends_on:
      - autozone_mongo

  autozone_mongo:
    image: mongo:7.0
    container_name: ${PROJECT_PREFIX:-}autozone_mongo
    hostname: ${PROJECT_PREFIX:-}autozone_mongo
    expose:
      - "27017"
    volumes:
      - autozone_mongo-data:/data/db
    restart: always
    networks:
      - autozone_network

  apigateway:
    depends_on:
      - autozone_api
    environment:
      - "SCV2_PROFILE_AUTOZONE=true"
      - "AUTOZONE_API_HOST=${PROJECT_PREFIX:-}autozone_api"
      - "AUTOZONE_API_PORT=4545"

networks:
  autozone_network:
    driver: bridge

volumes:
  autozone_mongo-data:
  autozone-data:

