version: "3.3"

x-pf-info:
  name: machine learning (ml) profile
  prompt: Enable the machine learning (ml) profile?
  description:
    The machine learning profile enables the machine learning service, used
    to enhance object classifications and detections within the webgui
    (service_classifier)
  settings:
    CLASSIFIER_TAG:
      default: "latest"

services:
  apigateway:
    depends_on:
      - service_classifier
    environment:
      - "SCV2_PROFILE_ML=true"
      - "CLASSIFIER_HOST=${PROJECT_PREFIX:-}service_classifier"
      - "CLASSIFIER_PORT=7373"

  service_classifier:
    container_name: ${PROJECT_PREFIX:-}service_classifier
    image: pacefactory/service-classifier:${CLASSIFIER_TAG:-latest}
    restart: always
    logging:
      driver: local
    depends_on:
      - dbserver
    ipc: host
    environment:
      - "DBSERVER_HOST=${PROJECT_PREFIX:-}dbserver"

    volumes:
      - service_classifier-data:/home/scv2/volume
    networks:
      - external_network

volumes:
  service_classifier-data:
