version: "3.3"

x-pf-info:
  name: HTTPS (GoDaddy)
  prompt: Enable HTTPS (via godaddy DNS, pacefactory.com domain)
  description:
    Provision HTTPS certificate via letsencrypt. 
    You MUST have already updated ./credentials/godaddy/credentials.ini with the appropriate secret and key.
  settings:
    SERVER_NAME:
      description: Final domain name will be SERVER_NAME.pacefactory.com
      default: ""
    LETSENCRYPT_EMAIL:
      description: Email address to use for letsencrypt.com
      default: ""      
    HTTPS_PORT:
      default: 443

services:
  certbot:
    profiles:
      - https-godaddy
    container_name: ${PROJECT_PREFIX:-}certbot
    image: miigotu/certbot-dns-godaddy
    command: 
      - "certbot"
      - "certonly"
      - "--authenticator"
      - "dns-godaddy"
      - "--dns-godaddy-propagation-seconds"
      - "900"      
      - "--dns-godaddy-credentials"
      - "/opt/godaddy/credentials.ini"
      - "--keep-until-expiring"
      - "--non-interactive"
      - "--expand"
      - "--agree-tos"
      - "--eff-email"      
      - "-m"
      - "${LETSENCRYPT_EMAIL}"
      - "-d"
      - "${SERVER_NAME}.pacefactory.com"
    logging:
      driver: local    
    volumes:
      - "./credentials/godaddy:/opt/godaddy/:ro"
      - certbot:/etc/letsencrypt/:rw      
      
  apigateway:
    ports:
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - certbot:/etc/nginx/ssl/:ro      
    environment:
      - "SCV2_PROFILE_SSL=true"
      - "SERVER_NAME=${SERVER_NAME}.pacefactory.com"

volumes:
  certbot: