x-pf-info:
  name: Service Ports
  prompt: Enable per-service ports for accessing dtree and gifwrapper utility interfaces?
  description:
    These are not strictly necessary, but make management easier. In a security
    constrained environment open ports can be disabled.
  settings:
    DTREESERVER_PUBLIC_PORT:
      default: 7272
    GIFWRAPPER_PUBLIC_PORT:
      default: 7171

services:
  service_gifwrapper:
    ports:
      - "${GIFWRAPPER_PUBLIC_PORT:-7171}:7171"
  service_dtreeserver:
    ports:
      - "${DTREESERVER_PUBLIC_PORT:-7272}:7272"
