version: "3.3"

x-pf-info:
  name: mosquitto profile
  prompt: Enable the mosquitto profile?
  description: The mosquitto profile enables the mosquitto mqtt broker
  settings:
    PF_MOSQUITTO_TAG:
      default: latest
    PF_MOSQUITTO_PUBLIC_PORT:
      default: 1883
    PF_MOSQUITTO_WEBSOCKETS_PORT:
      default: 7575

services:
  pf_mosquitto:
    container_name: ${PROJECT_PREFIX:-}pf_mosquitto
    hostname: ${PROJECT_PREFIX:-}pf_mosquitto
    image: pacefactory/pf_mosquitto:${PF_MOSQUITTO_TAG:-latest}
    restart: always
    logging:
      driver: local
    volumes:
      - mosquitto-data:/mosquitto
    ports:
      - "${PF_MOSQUITTO_PUBLIC_PORT:-1883}:1883"
      - "${PF_MOSQUITTO_WEBSOCKETS_PORT:-7575}:7575"
    networks:
      - external_network

  apigateway:
    depends_on:
      - pf_mosquitto
    environment:
      - "SCV2_PROFILE_PF_MOSQUITTO=true"
      - "PF_MOSQUITTO_HOST=${PROJECT_PREFIX:-}pf_mosquitto"
      - "PF_MOSQUITTO_PORT=1883"
      - "PF_MOSQUITTO_WEBSOCKETS_PORT=7575"

  service_audit_processing:
    depends_on:
      - pf_mosquitto
    environment:
      - "PF_MQTT_URL=http://${PROJECT_PREFIX:-}pf_mosquitto:${PF_MOSQUITTO_PUBLIC_PORT:-1883}"

volumes:
  mosquitto-data:
