version: "3.3"

x-pf-info:
  name: swift labeler profile
  prompt: Enable the swift labeler profile?
  description:
    Swift labeler service supports quick annotation of objects to
    train both a spaghetti classifier and tiny image classifier
  settings:
    SWIFT_TAG:
      default: "latest"

services:
  apigateway:
    depends_on:
      - service_swift_labeler
    environment:
      - "SCV2_PROFILE_SWIFT=true"
      # TODO: Support project prefix as below
      - "SWIFT_HOST=swiftlabeler"
      - "SWIFT_PORT=7474"
    volumes:
      - service_swift_labeler-static:/www/static/swift-static:ro

  service_audit_processing:
    depends_on:
      - service_swift_labeler
    environment:
    # TODO: Support project prefix as below
      - "PF_SWIFT_URL=http://swiftlabeler:${SWIFT_PORT:-7474}"

  # TODO: Will need to add environment for auditgui

  service_swift_labeler:
    container_name: ${PROJECT_PREFIX:-}service_swift_labeler
    # Edge case: need to use RFC compliant hostname (i.e. no underscores), otherwise Django yells at us
    # https://stackoverflow.com/questions/52997543/invalid-http-host-header-the-domain-name-provided-is-not-valid-requests-to-d
    # TODO: Need to support project prefix somehow... which currently allows _ in the name
    hostname: swiftlabeler
    image: pacefactory/swift-labeler:${SWIFT_TAG:-latest}
    restart: always
    logging:
      driver: local
    depends_on:
      - dbserver
    environment:
      - "DBSERVER_HOST=${PROJECT_PREFIX:-}dbserver"
      - "DEBUG=false"
      - "APIGATEWAY=true"
      - "BASE_PATH=api/swift/"
    volumes:
      - service_swift_labeler-data:/home/scv2/volume
      - service_swift_labeler-static:/home/scv2/static:rw
    networks:
      - external_network

volumes:
  service_swift_labeler-data:
  service_swift_labeler-static:
